### PR TITLE
fix rtl8812au, rtl88x2bu driver build

### PR DESCRIPTION
**Pull request by makigumo**
This seems to fix the build, I can now see the relevant driver files being built in the log output.

Here is a kernel with rtl8812au builtin and rtl88x2bu as a module. Please test it.

[zImage_dtb.zip](https://github.com/MiSTer-devel/Linux-Kernel_4.5.0_MiSTer/files/2770965/zImage_dtb.zip)

### CODE REVIEW

**Comment by sorgelig** [comment]
so, for rtl88x2bu i have to use insmod with every boot?

**Comment by sorgelig** [comment]
rtl88x2bu works. 
Now need to figure out how to make it built-in together with rtl8812au

**Comment by makigumo** [comment]
With the current versions of both drivers it doesn't seem possible to use them as builtin drivers. The linker complains about a lot of duplicated symbols otherwise. If the drivers common code is similar enough it might be feasible to try to integrate them. But I fear their versions (4.x and 5.x) are too far apart. So, for now, there can only be one of the drivers builtin. But there are usually some ways to automatically load the module during boot.

The newer rtl8812au disabled support, I'm not really sure, for rtl8821a, so that could be a problem. Is your device recognized?

The `firmware` folder was removed upstream, with the hint to rely on the firmware packaged provided by the distributions (https://github.com/torvalds/linux/commit/5620a0d1aacd554ebebcff373e31107bb1ef7769).

RTC probably needs just some additional configuration. I will try to have a look later.

**Comment by sorgelig** [comment]
Probably it's fine for Linus to scrap the whole firmware. But now we are those who provide the distribution. So we need to determine which firmwares to include... May be it's better to re-add required firmware to firmware folder.

Making driver as a module is not a good thing. It increases both loading time and footprint (8822bu alone is only twice smaller than the zImage). I'm working on integrating both drivers as built-in. Hope i will succeed. I'm doing it on 4.5 version for now.

about RTC. Due to problems with DW I2C device, i had to switch it to bitbanging mode. Just for your note.

**Comment by sorgelig** [comment]
succeed! both 8812AU and 8822BU now can be built-in in v4.5

**Comment by makigumo** [comment]
In `> Device Drivers > I2C support > I2C Hardware Bus support` the `Altera Soft IP I2C` (or `CONFIG_I2C_ALTERA=y` in the config) is currently unchecked. This could by a likely candidate.

I don't have an IO-board, is there another way to test it?

**Comment by sorgelig** [comment]
RTC is separate board connected to small LTC header. Basically any I2C clock with appropriate driver should work.
Altera Soft IP I2C is not relevant.
May be something in device tree description.

**Pull request merged**
